package vista;

import java.awt.Color;

/**
 *Form APPForm
 * @authors Diego Araya & Raul Alfaro
 */
public class AppForm extends javax.swing.JFrame {

    /**
     * Creates new form AppForm
     */
    public AppForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        boxTipoOperacion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        boxAlgoritmo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSalida = new javax.swing.JTextField();
        btAplicarAlgoritmo = new javax.swing.JButton();
        btEnviarPorCorreo = new javax.swing.JButton();
        btSALIR = new javax.swing.JButton();
        btLimpiarTxt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel1.setText("Encrypt App");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel2.setText("Operacion a realizar :");

        boxTipoOperacion.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        boxTipoOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Encriptar", "Desencriptar", " " }));
        boxTipoOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoOperacionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel3.setText("Algoritmo :");

        boxAlgoritmo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        boxAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cesár", "Llave", "Vigenére", "Palabra Inversa", "Mensaje Inverso", "Codificación Binaria", "RSA", "DES", "AES" }));
        boxAlgoritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAlgoritmoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel4.setText("Entrada :");

        txtEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel5.setText("Salida :");

        txtSalida.setEditable(false);
        txtSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalidaActionPerformed(evt);
            }
        });

        btAplicarAlgoritmo.setBackground(new java.awt.Color(204, 204, 204));
        btAplicarAlgoritmo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btAplicarAlgoritmo.setText("Aplicar Algoritmo");

        btEnviarPorCorreo.setBackground(new java.awt.Color(204, 204, 204));
        btEnviarPorCorreo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btEnviarPorCorreo.setText("Enviar por Correo");
        btEnviarPorCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarPorCorreoActionPerformed(evt);
            }
        });

        btSALIR.setBackground(new java.awt.Color(204, 204, 204));
        btSALIR.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btSALIR.setText("SALIR");
        btSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSALIRActionPerformed(evt);
            }
        });

        btLimpiarTxt.setBackground(new java.awt.Color(204, 204, 204));
        btLimpiarTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btLimpiarTxt.setText("Limpiar Texto");
        btLimpiarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSALIR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btLimpiarTxt)
                                .addGap(241, 241, 241)
                                .addComponent(btEnviarPorCorreo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(36, 36, 36)
                                        .addComponent(boxTipoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(240, 240, 240)
                                        .addComponent(jLabel3)
                                        .addGap(49, 49, 49)
                                        .addComponent(boxAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(287, 287, 287)
                                        .addComponent(btAplicarAlgoritmo)))
                                .addGap(0, 12, Short.MAX_VALUE)))))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(boxTipoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(boxAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSALIR)
                            .addComponent(btEnviarPorCorreo)
                            .addComponent(btLimpiarTxt))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAplicarAlgoritmo)
                        .addGap(229, 229, 229))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxTipoOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTipoOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTipoOperacionActionPerformed

    private void boxAlgoritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAlgoritmoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxAlgoritmoActionPerformed

    private void txtEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaActionPerformed

    private void txtSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalidaActionPerformed

    private void btEnviarPorCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarPorCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEnviarPorCorreoActionPerformed

    private void btSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSALIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSALIRActionPerformed

    private void btLimpiarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLimpiarTxtActionPerformed
    
    public boolean datosCorrectos(){
      String entrada = txtEntrada.getText();
      return !entrada.isEmpty();
    }
    
    public void salir(){
      System.exit(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boxAlgoritmo;
    public javax.swing.JComboBox<String> boxTipoOperacion;
    public javax.swing.JButton btAplicarAlgoritmo;
    public javax.swing.JButton btEnviarPorCorreo;
    public javax.swing.JButton btLimpiarTxt;
    public javax.swing.JButton btSALIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField txtEntrada;
    public javax.swing.JTextField txtSalida;
    // End of variables declaration//GEN-END:variables
}
